---
- name: Install HTTPD
  hosts: all
  become: yes
  vars:
    apache_listen_port: 8080
    apache_vhosts:
      - {servername: "example.com", documentroot: "/var/www/vhosts/example_com"}
  roles:
    - { role: geerlingguy.apache }
